name = "logwhisperer"
main = "src/index.ts"
compatibility_date = "2025-10-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDO"

[[kv_namespaces]]
binding = "CFG_KV"
id = "8bb2505902bf49a2992bd297158a5d11"

[[d1_databases]]
binding = "LOGDB"
database_name = "logwhisperer_db"
database_id = "fe9e777d-9274-41b0-902f-b2a8e402f9bc"

[[vectorize]]
binding = "PATTERNS_INDEX"
index_name = "log_patterns"

[[r2_buckets]]
binding = "LOGR2"
bucket_name = "logwhisperer-uploads"

[[workflows]]
name = "logwhisperer-pipeline"
binding = "PIPELINE"
class_name = "LogWhispererPipeline"
script_name = "src/workflows.ts"

[vars]
MAX_TOKENS = "2048"
SAFE_COMMANDS_ALLOWLIST = "iptables,ip,ufw,nft,cisco,netsh,powershell,systemctl,route"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]
